version: '3.5'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    hostname: db
    container_name: db
    environment:
      POSTGRES_USER: web_price
      POSTGRES_PASSWORD: web_price
      POSTGRES_DB: web_price
    networks:
      backend:
        aliases:
          - postgres
    restart: unless-stopped
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "
      python manage.py collectstatic --noinput &&
      pwd && 
      uwsgi --ini uswgi.ini
      "
    hostname: api
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/api
      - sockets:/sockets/
      - statics:/api/static/
    networks:
      backend:
        aliases:
          - api
    restart: unless-stopped
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    hostname: web
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:127.0.0.1"
    env_file:
      - ./web/.env
    volumes:
      - www:/usr/share/nginx/html/
    networks:
      backend:
        aliases:
          - web
    restart: unless-stopped
  app:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - sockets:/sockets/
      - www:/usr/share/nginx/html/
      - statics:/usr/share/nginx/html/statics/
    depends_on:
      - api
      - web
volumes:
  sockets:
  www:
  statics:
networks:
  backend:
    name: backend
    driver: bridge