# Generated by Django 5.0.1 on 2024-01-31 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "erp_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ERP code"
                    ),
                ),
                ("started_at", models.DateField(verbose_name="Started at")),
                ("expire_at", models.DateField(verbose_name="Expire at")),
                (
                    "recommendation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Recommendation"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("no_waiting", "No waiting"),
                        ],
                        default="normal",
                        max_length=255,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("filling_in", "Filling in"),
                            ("finished", "Finished"),
                            ("canceled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.buyer",
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.company",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="common.payment",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "payment_refer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payment_refers",
                        to="common.payment",
                        verbose_name="Payment refer",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
            },
        ),
        migrations.CreateModel(
            name="PriceItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "erp_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ERP code"
                    ),
                ),
                (
                    "product_observation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Product observation"
                    ),
                ),
                (
                    "quantity_refer",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Quantity refer"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unitary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Unitary",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Tax",
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Shipping",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Discount",
                    ),
                ),
                (
                    "rounding",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Rounding",
                    ),
                ),
                (
                    "supplier_observation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Supplier observation"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.company",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="price.price",
                        verbose_name="Price",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "unity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.unity",
                        verbose_name="Unity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Item",
                "verbose_name_plural": "Price Items",
            },
        ),
    ]
