# Generated by Django 5.0.1 on 2024-01-27 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("started_at", models.DateField()),
                ("expire_at", models.DateField()),
                ("recommendation", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("no_waiting", "No waiting"),
                        ],
                        default="normal",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("filling_in", "Filling in"),
                            ("finished", "Finished"),
                            ("canceled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=255,
                    ),
                ),
                ("erp_code", models.CharField(max_length=255, unique=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.buyer",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.company",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="common.payment",
                    ),
                ),
                (
                    "payment_refer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payment_refers",
                        to="common.payment",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.supplier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PriceItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("product_observation", models.TextField(blank=True, null=True)),
                (
                    "quantity_refer",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=15)),
                ("unitary", models.DecimalField(decimal_places=6, max_digits=15)),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "rounding",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("supplier_observation", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="base.company",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="price.price"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.product",
                    ),
                ),
                (
                    "unity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.unity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
