# Generated by Django 5.0.2 on 2024-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0002_alter_priceitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceitem",
            name="filled",
            field=models.BooleanField(default=False, verbose_name="Filled"),
        ),
    ]
