# Generated by Django 5.0.2 on 2024-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0004_price_buyer_email_price_supplier_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceitem",
            name="buyer_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Buyer email denormalized",
            ),
        ),
        migrations.AddField(
            model_name="priceitem",
            name="supplier_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Supplier email denormalized",
            ),
        ),
    ]
