# Generated by Django 5.0.2 on 2024-03-12 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0005_priceitem_buyer_email_priceitem_supplier_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Discount applied on all items",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Discount percent applied on all items",
            ),
        ),
        migrations.AddField(
            model_name="priceitem",
            name="discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=2,
                null=True,
                verbose_name="Discount percent",
            ),
        ),
    ]
