# Generated by Django 5.0.1 on 2024-01-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="erp_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ERP code"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="erp_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ERP code"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="erp_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ERP code"
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="erp_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ERP code"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="erp_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ERP code"
            ),
        ),
        migrations.AlterField(
            model_name="unity",
            name="erp_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ERP code"
            ),
        ),
    ]
